<template>
  <div class="loadingio-spinner-rolling-x7tker1jymh">
    <div class="ldio-s5lkn1vdhk9">
      <div></div>
    </div>
  </div>
</template>
<style type="text/css">
@keyframes ldio-s5lkn1vdhk9 {
  0% {
    transform: translate(-50%, -50%) rotate(0deg);
  }
  100% {
    transform: translate(-50%, -50%) rotate(360deg);
  }
}
.ldio-s5lkn1vdhk9 div {
  position: absolute;
  width: 60px;
  height: 60px;
  border: 10px solid #5b10ff;
  border-top-color: transparent;
  border-radius: 50%;
}
.ldio-s5lkn1vdhk9 div {
  animation: ldio-s5lkn1vdhk9 1s linear infinite;
  top: 50px;
  left: 50px;
}
.loadingio-spinner-rolling-x7tker1jymh {
  width: 30px;
  height: 30px;
  display: inline-block;
  overflow: hidden;
  background: transparent;
}
.ldio-s5lkn1vdhk9 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.3);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-s5lkn1vdhk9 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>